version: "3"

services:
  frontend:
     build:
       context: ./sys-stats
     restart: always
     ports:
       - "3000:3000"
     links:
        - backend
     container_name: frontend
  backend:
     build: .
     restart: always
     ports:
       - "8000:8000"
     container_name: backend